  pip_audit:
    runs-on: ubuntu-latest
    needs: build_test
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: requirements.txt

      - name: Install deps
        run: |
          pip install -r requirements.txt
          # гарантируем поддержку SARIF
          pip install "pip-audit>=2.7.0"

      - name: Run pip-audit (SARIF)
        run: |
          set -e
          # пытаемся создать SARIF; не падаем на не-нулевом коде
          pip-audit -r requirements.txt -f sarif -o pip-audit.sarif || true
          # если файл не создан или пустой — кладём минимальный валидный SARIF
          if [ ! -s pip-audit.sarif ]; then
            echo "::warning::pip-audit did not produce SARIF; creating empty report"
            cat > pip-audit.sarif <<'SARIF'
            {
              "version": "2.1.0",
              "$schema": "https://json.schemastore.org/sarif-2.1.0.json",
              "runs": [
                {
                  "tool": {
                    "driver": {
                      "name": "pip-audit",
                      "informationUri": "https://github.com/pypa/pip-audit",
                      "rules": []
                    }
                  },
                  "results": []
                }
              ]
            }
SARIF
          fi

      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: pip-audit.sarif

      - uses: actions/upload-artifact@v4
        with:
          name: pip_audit
          path: pip-audit.sarif

